### ISSUE TITLE
Default path for prototype admin pages

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-prototype-rig#124]
Currently the following prototype admin pages are provided (or will soon be provided):

* `/clear-session-data `
* `/feature-flags`
* `/password`

These could clash with routes used in a prototype. Options:

1. Rename these routes so they are more unique (prefix with `_`?)
2. Default to serving these pages on a particular path (`/prototype-admin/*`)
3. Maintain current paths, but allow a path to configured

**Comment by fofr** [comment]
`/password` feels like the only one that's likely to clash.

**Comment by paulrobertlloyd** [comment]
Maybe option 4: rename route for password to something like `/prototype-sign-in`.

**Comment by paulrobertlloyd** [comment]
Closing. Will use `/prototype-password` as a unique name for this built-in route.
