### ISSUE TITLE
Making this repo a template

### ISSUE THREAD

**Issue by peteryates** [x-govuk/govuk-prototype-rig#135]
This looks like an ideal way to get people started with prototyping on Codespaces (it works with one click!), it would be great if the process of getting their own fork was a little easier. GitHub only supports one fork per organisation so to get their own copy to practice on people would need to clone and push to an empty project.

This can be made easier by [making the template a prototype](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository). This adds a button on the project homepage that creates a fresh copy of the project with no shared commit history - perfect for learners.

Thanks!

**Comment by paulrobertlloyd** [comment]
This repo was originally a template, but is now the space where the package is developed (and will become a sort of mono repo given a second package in development that enables the use of `npm init govuk-prototype-rig [DIRECTORY_NAME]`. Therefore it doesn’t make sense to make it a template, as much of the code is not relevant to most users.

@fofr has created a template repo off the back of this (https://github.com/fofr/govuk-prototype-rig-template), although I note that this isn’t set up as a template repo, yet.

Once v1.0 has been released, no reason why we can’t maintain an ‘official’ separate template repo on X-GOVUK, though.

**Comment by peteryates** [comment]
Ah, thanks for elaborating!

Really impressive work here by the way, was up and running in seconds and everything's laid out sensibly - it just worked.

**Comment by fofr** [comment]
I've updated https://github.com/fofr/govuk-prototype-rig-template and set up as a template repo
