### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME on Windows

### ISSUE THREAD

**Issue by clinkingdog** [x-govuk/govuk-prototype-rig#161]
When following the instructions to run a new prototype install, my `npm start` fails with the following error (at the "serve" step):

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:372:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
    at defaultResolve (node:internal/modules/esm/resolve:1200:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ESMLoader.import (node:internal/modules/esm/loader:380:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at file:///C:/Users/NicGol/OneDrive%20-%20Softwire%20Technology%20Limited/Work/DLUHC/Core%20Delta/Prototype/submit-social-housing-lettings-and-sales-data-prototype/node_modules/govuk-prototype-rig/lib/server.js:126:21 {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

My colleagues (who are all using Macs or Linux) suggest this is an error caused by Windows-style file references and may therefore be present for anyone who tries to use the prototype rig on Windows (but I have no evidence either way, only my own experience).

This does not happen with the prototype **kit**, only with the prototype **rig**.

I ran the `npm install` before the `npm start` as per the instructions. I also tried running an `npm update` after the install as per issue #155 in case that was related, but it didn't help.

I have just joined a project based on this rig (but the error occurs even with a clean rig install) and am currently unable to work on the prototype, so I'd be very grateful if anyone can offer some advice soon! Thanks :)

**Comment by paulrobertlloyd** [comment]
Hi @clinkingdog. What version of Node do you have installed? You should be able to find this out by typing `node -v` on the command line.

**Comment by clinkingdog** [comment]
Thanks @paulrobertlloyd for the quick response. I was originally using a fresh install of 16.16.0 LTS, and got the error there. I tried updating to 18.7.0 Current in case that solved the issue, but I get the same symptom.

**Comment by paulrobertlloyd** [comment]
Sorry, don’t quite understand; are you seeing the issue above, or a different issue?

**Comment by clinkingdog** [comment]
I see the issue in my OP in both versions.

**Comment by paulrobertlloyd** [comment]
Think I’ve found the issue, but don’t have a Windows computer to hand to test. Try upgrading to `0.8.2` and let me know if this issue still occurs.

**Comment by clinkingdog** [comment]
That's fixed it. Thanks so much @paulrobertlloyd!

**Comment by paulrobertlloyd** [comment]
Brill! Thanks for reporting!
