### ISSUE TITLE
RFC: Pulling down the rigging

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-prototype-rig#201]
Since the Prototype Rig was created, a number of things have changed:

* The GOV.UK Prototype Kit is being actively developed again, and many of the chief complaints have been addressed.
* GOV.UK Prototype Kit now provides an official plugin system, providing lots of hooks which can be used to add features that are in the Rig but not currently in the Kit.
* Maintaining the GOV.UK Eleventy Plugin, GOV.UK Design History and all the different packages that support the Rig can be a little burdensome. Especially true when these share a number of similar workflows, dependencies and documentation tooling.
* Turns out maintaining a prototyping platform relied upon by even a handful of teams in government is not fun, less so given an alternative is (again fully) supported by GDS.
* Releasing v1.0 of this project has been stalled by trying to create an initialiser script that copies a set of base files for starting a new prototype. The Prototype Kit now offers a similar feature, arguably in a much more considered and user-friendly way.
* A number of existing open issues relate to incorporating changes already made in GOV.UK Prototype Kit
* Documentation for the GOV.UK Prototype Wizard lives on the documentation site for the Rig. Meanwhile a separate site is required for the GOV.UK Prototype Components.

Rather than continue developing this hard fork, I propose the following:

1. Create a new repository with a mono repo structure and use it to manage all X-GOVUK packages that are plugins for the GOV.UK Prototype Kit.
2. Extract features from the GOV.UK Prototype Rig, convert them into plugins and add them to this new mono repo.
3. Split GOV.UK Prototype Components into packages that provide a plugin for each component, and archive its repository.
4. Retire GOV.UK Prototype Rig, and archive its repository.

### Setup new mono repository that provides shared resources

* Licence (MIT)
* Linting (Standard and StyleLint)
* Testing (Node test runner)
* Documentation (Eleventy and GOV.UK Eleventy Plugin)
* Dependencies (NPM workspaces)
* Package publishing (Lerna)
* CI (GitHub Actions)
* Hosting (GitHub Pages)

### Existing packages merged into new mono repo

2 existing repositories archived, and packages moved into and published from new mono repo:

* `govuk-prototype-wizard`
* `task-list-component`

Test validity of new approach with minor version bumps of these packages, and documentation for Wizard published at new location.

### New packages extracted from GOV.UK Prototype Components

7 new packages managed in and published from mono repo:

* `govuk-prototype-component-autocomplete`
* `govuk-prototype-component-masthead`
* `govuk-prototype-component-primary-navigation`
* `govuk-prototype-component-related-navigation`
* `govuk-prototype-component-sub-navigation`
* `govuk-prototype-edge`
* `govuk-prototype-warn-on-save`

Release v0.1 for each plugin, and documentation for components published at new location.

### New packages extracted from GOV.UK Prototype Rig

3 new packages managed in and published from mono repo:

* `govuk-prototype-filters`
* `govuk-prototype-feature-flags`
* `govuk-prototype-form-validation`

Release v0.1 for each plugin, and documentation for features published at new location.

### Release packages on NPM

Use the same version number for all packages published from mono repo:

* All packages published as v1.0.0
* Documentation site launched

## Benefits

1. One repository to manage. Can make changes to multiple packages and bump their versions simultaneously.
2. Easier to provide and host documentation, rather than have it split up among different repos and websites.
3. Authors have a greater choice about which packages/plugins they include in their prototypes.
4. Consolidates all of X-GOVUK’s prototype-related projects

## Downsides

1. Authors may need to add and manage a greater number of packages in their prototype project
2. Time and effort required to transition to new structure
3. 4 project repos would be archived and 2 npm packages would be no longer maintained (Rig and Components).

## Name

Maybe `GOV.UK Prototype Toolkit`? Or could reuse the Rig name, but might that cause confusion?

**Comment by paulrobertlloyd** [comment]
@paulrobertlloyd @frankieroberto @nataliecarey Thoughts on the above. Does this make sense? More hassle than it’s worth?

**Comment by frankieroberto** [comment]
@paulrobertlloyd interesting idea! I must admit I’m not super familiar with the practice of having a single "mono" repository from which multiple packages are published (although I think Rails does this with their ruby gems?).

One of the downsides I can see is that it means any change to any of the components means publishing a new version for all of them, which means more dependabot updates, and also some release notes which have no content at all? Unless you’re suggesting that this would just be the initial release, and after that they’d each be on their own release cycle?

The other downside might be that you couldn't install an npm package using a [Git URL as a dependency](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#git-urls-as-dependencies), eg if you wanted to test an unreleased version – but that might not be super common anyway.

Otherwise, I like the idea of having each component as its own package - it might make people more comfortable with installing them? We could also ask @nataliecarey if the prototype kit team would be comfortable with making them more discoverable by advertising them in the "Available plugins" list in the prototype kit admin page?

**Comment by paulrobertlloyd** [comment]
> One of the downsides I can see is that it means any change to any of the components means publishing a new version for all of them.

[Lerna has fixed or independent modes](https://lerna.js.org/docs/features/version-and-publish) for publishing packages within a mono repo.

The fixed mode is useful for projects like [Indiekit](https://github.com/getindiekit/indiekit) which I have setup using a mono repo as there are inter-dependencies between packages. But in this context, where the plugins are dependent on external packages (`govuk-frontend`, `govuk-prototype-kit`) not each other, maybe independent versioning would work better?

> The other downside might be that you couldn't install an npm package using a [Git URL as a dependency](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#git-urls-as-dependencies)

Ah yes, this is an issue. But, there are workarounds. [GitPkg](https://gitpkg.vercel.app/guide/) looks very useful in this regard.

**Comment by nataliecarey** [comment]
Thanks for the mention. I'm answering in two different capabilities here - I'm now the tech lead for the prototype kit but I've also been involved with the unofficial x-govuk. I'm mostly answering unofficially but from the context of being involved in running the GOV.UK kit.

The semi-official part: As far as I'm concerned v13 of the kit is a really positive direction, we're keen on hearing about what's missing and improving the plug-in framework to make it easier for people to make the customisations they need as well as sharing common tools. We're discussing how far we should push that as pushing it too far might create too much difference between different kits making it difficult for people to move from one project to another. We're planning to produce documentation for creating plug-ins and I'm personally very keen on running sessions to teach plug-in developers about the options available to them. If you're interested in those sessions let me know and I'll raise it with the team.

The completely unofficial part: personally I prefer individual repos, I find them easier to work with and problems like a combined documentation site can be solved with automation... But I understand why some people prefer mono-repo. Installing from a branch as an nom dependency is *such* a useful feature, it's often under-utilised.

It's worth noting that plug-in upgrades now happen in the browser so it becomes really easy for people to stay up-to-date with new plug-in releases. With that system I appreciate for more smaller plug-ins but there are pros and cons of that approach.

I think the direction you're suggesting is a positive one, personally I'm really pleased to hear that it's become more compelling to move back to the standard kit and if there's anything I can do to support that please let me know.

**Comment by frankieroberto** [comment]
@nataliecarey have you decided yet what the criteria or process will be for listing available plugins within the kit’s admin screens?

**Comment by nataliecarey** [comment]
We haven't, if that decision impacts this one I can ask to prioritise our discussion on it.

**Comment by paulrobertlloyd** [comment]
> We're planning to produce documentation for creating plug-ins and I'm personally very keen on running sessions to teach plug-in developers about the options available to them. If you're interested in those sessions let me know and I'll raise it with the team.

@nataliecarey Count me in!

> The completely unofficial part: personally I prefer individual repos, I find them easier to work with and problems like a combined documentation site can be solved with automation.

Yeah, I can understand that. As I mentioned, my experience using a mono repo has been with a project that, while doesn’t have strict dependencies between modules, shares enough of the same underlying architecture that it makes sense to manage all the different packages in one place. Maybe Prototype Kit plugins don’t have that problem.

I don’t mind separate repos, but I start to worry a bit especially if there’s lots of components, each with their own repo each that share a lot of the same boilerplate and tooling, that to keep on top of requires repeating the same steps in multiple places.

Maybe there’s a middle ground, some of these components are bundled together in once place, some are not.

Curious if you’ve got any recommendations for automating publishing documentation that sits across different repos? Off the top of my head, might be possible fetch data using the GutHub API, but that may be overkill!

**Comment by frankieroberto** [comment]
How about we could, as a transitional approach, keep [govuk-prototype-components](https://github.com/x-govuk/govuk-prototype-components) as a single repo, but with the individual components published as separate npm packages - but leave the 2 existing repos (`govuk-prototype-wizard` and `task-list-component`) as separate repos + packages?

Then we could evaluate from there, and either move the components out into a separate repo one-by-one, or leave them where they are, depending on how the experience goes?

I’m not as familiar with `[govuk-prototype-rig](https://github.com/x-govuk/govuk-prototype-rig)` so I'm not sure how easy it'd be to extract features from that into plugins?

**Comment by paulrobertlloyd** [comment]
> How about we could, as a transitional approach, keep [govuk-prototype-components](https://github.com/x-govuk/govuk-prototype-components) as a single repo, but with the individual components published as separate npm packages

That may be a good approach to start off with. I'm still not clear what the use cases or benefits are of having components as separate packages though? Does it matter if all components are included in a project? I don't use half of the components in GOV.UK Frontend either, but they’re all in the same package.

> I'm not sure how easy it'd be to extract features from that into plugins?

I’m not entirely sure either! Filters are high on my list for making a plugin, and it's clear how these can be plug-in-ified. I think form validation is a question of inserting a script in the footer of layouts, though without decorated components by default, a little more work required to get working. Feature flags might be a little more difficult/convoluted too.

**Comment by nataliecarey** [comment]
(having just checked what's public on our GitHub issues list) if you have an autocomplete that's ready to go (after adjusting it for v13) then it could be a good time to discuss that. (https://github.com/alphagov/govuk-prototype-kit/issues/974)

From my perspective, when we're looking at which plug-ins to add to the "available plug-ins" list (in its current form) I would find it more compelling to have fewer plug-ins which each do more rather than more single purpose plug-ins. Right now the "available plug-ins" is behaving as a list of recommended plug-ins but as the list grows that won't be viable, I can see us ending up with (hopefully searchable) pages of available plug-ins and a shorter list of recommended plug-ins but we haven't had a need to discuss it yet so I can't say how we'll handle it in the end. It's also worth noting that people can install any plug-in even if it's not in our list.

If the way we'd handle/display multiple plug-ins is going to make a difference to your decision I'd suggest we have a meeting so you've got the best information possible to make that decision.

**Comment by paulrobertlloyd** [comment]
Revised, simpler proposal:

### govuk-prototype-components
* Leave as is, with 1 package and exposed as a Prototype Kit plugin
* v2.0 removes Summary Card and Task List components
* Decide if `task-list-component` should be moved into this package

### govuk-prototype-wizard
* No Prototype Kit plugin needed (imported and used exclusively within routes)
* Add documentation site (moving content over from Rig documentation – or maybe the `README.md` is enough?)

### govuk-prototype-filters
* New repo
* Provides Prototype Kit plugin to add filters to a prototype
* Has its own documentation site (moving content over from Rig documentation)
  
### govuk-decorated-components
* Not possible to make compatible with Prototype Kit v13
* Decide if should add decorate filter to above filters package, and retire this project.
  
### govuk-prototype-rig
* Archive and retire, with remaining features made into plugins if possible (which could potentially all live in the same repo/package)

**Comment by frankieroberto** [comment]
@paulrobertlloyd sounds good to me 👍

The filters plugin will be super useful.

**Comment by frankieroberto** [comment]
@paulrobertlloyd I just learnt that the version 13 of the prototype kit has some magic which means you no longer need to set `value` attributes, but instead they get filled in automatically from the data, by using the `name` attribute! I think this removes the need for the decorate filter?

**Comment by paulrobertlloyd** [comment]
Ooooh, will try. If so, many headaches go away!

**Comment by frankieroberto** [comment]
oh wait, false alarm, it doesn't do it - I misunderstood something.

There is a newish easier way to set checked values on checkboxes though:

```
{{ govukCheckboxes({
        name: "things",
        values: data.things,
        items: [{
          value: "a",
          text: "A"
        }, {
          value: "b",
          text: "B"
        }, {
          value: "c",
          text: "C"
        }]
      }) }}
```

**Comment by nataliecarey** [comment]
However much I'd like to take credit for that it was a change in govuk-frontend.

**Comment by paulrobertlloyd** [comment]
Ah, right. That’s already captured here: https://github.com/x-govuk/govuk-decorated-components/issues/1

The decorated components project isn’t compatible with GOV.UK Prototype Kit v13, at least on first investigation, as it attempts to replace the existing form components by using their component names; haven’t been able to do that with the new way components are loaded. It’s a massive hack, so there is an argument perhaps that it shouldn't be allowed to work.

A bit of research needs to be done on what's the best way to do decorated components in 2023 - @nataliecarey if you have any ideas how this can be achieved, I’m all ears!

**Comment by frankieroberto** [comment]
I think _ideally_ the prototype kit would do something clever and would automatically set the `checked` or `value` attributes using the session `data` object (unless it was set manually). But I’ve no idea how easy that’d be...

**Comment by nataliecarey** [comment]
We've discussed doing it for the user and there are so many things to consider. I'll have a chat with the team about it this week.

As a general rule everything from plug-ins should be namespace so someone can choose to use `govukRadios` for the official one or `xGovukRadios` for the unofficial one.

**Comment by joelanman** [comment]
populating the data in components automatically is something we'd like to investigate - there is an old PR investigating it here:
https://github.com/alphagov/govuk-prototype-kit/pull/1316
